### ISSUE TITLE
你这个树形图 要是层级不确定 list包裹list 可能是层层包裹 怎么办

### ISSUE THREAD

**Issue by 4what2do** [shineM/TreeView#10]

**Comment by shineM** [comment]
层级不确定就没办法生成树形结构了   至于后面的list包裹list我不知道是什么意思

**Comment by 4what2do** [comment]
就像一个公司有N个部门，每个部门下又有几个下属的子部门，每个子部门可能又有几个下属小部门，不确定有几层，不止三层。

**Comment by shineM** [comment]
当你拿到数据的时候你肯定确定每一个部门属于几级吧

**Comment by 4what2do** [comment]
我再想想 有点转牛角尖了

**Comment by shineM** [comment]
嗯  有问题再open issue吧
