### ISSUE TITLE
android 4.4.2 闪退

### ISSUE THREAD

**Issue by MALTF** [shineM/TreeView#2]
安装不了
Could not find method android.view.Window.setStatusBarColor, referenced from method me.texy.treeviewdemo.MainActivity.setLightStatusBar
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

**Comment by shineM** [comment]
已修复Demo在SDK 23以下的问题 @malxue

**Comment by MALTF** [comment]
谢谢
