### ISSUE TITLE
如何默认展开第一项 且点击也是无法关闭

### ISSUE THREAD

**Issue by 1455459550** [shineM/TreeView#26]

**Comment by shineM** [comment]
构造的时候 treeNode.setExpande(true) 就是默认展开了;
treeNode.setItemClickEnable 就能阻止点击关闭了

**Comment by 1455459550** [comment]
我代码是这样的 但是没有起效果不知为何？
        root = TreeNode.root();
//        设置数据源
        buildTree();
        treeView = new TreeView(root, this, new MyNodeViewFactory());
        View view = treeView.getView();
//        展开第一级 且不能关闭
        root.setExpanded(true);
        root.setItemClickEnable(false);
        view.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        viewGroup.addView(view);

**Comment by shineM** [comment]
View view = treeView.getView(); 放到 set 后面试试

**Comment by 1455459550** [comment]
还是没有效果
     root = TreeNode.root();
//        设置数据源
        buildTree();
        treeView = new TreeView(root, this, new MyNodeViewFactory());
//        展开第一级 且不能关闭
        root.setExpanded(true);
        root.setItemClickEnable(false);
        View view = treeView.getView();
        view.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        viewGroup.addView(view);

**Comment by 1455459550** [comment]
treeView.expandLevel(0);  
我用的这个方法是展开第一项

**Comment by 1455459550** [comment]
但是点击无法关闭 我就不知道改哪里了

**Comment by 1455459550** [comment]
我知道在哪里修改了

**Comment by shineM** [comment]
你不应该 set 给 root，而是第一级的所有节点

**Comment by 1455459550** [comment]
达到我想要的效果了

**Comment by 1455459550** [comment]
嗯嗯 确实是  在数据源那边 我添加这个监听   
         for (int i = 0; i < 10; i++) {
            TreeNode treeNode = new TreeNode(new String("Parent  " + "No." + i));
            treeNode.setLevel(0);
            treeNode.setItemClickEnable(false);
            for (int j = 0; j < 10; j++) {
                TreeNode treeNode1 = new TreeNode(new String("Child " + "No." + j));
                treeNode1.setLevel(1);
                for (int k = 0; k < 5; k++) {
                    TreeNode treeNode2 = new TreeNode(new String("Grand Child " + "No." + k));
                    treeNode2.setLevel(2);
                    treeNode1.addChild(treeNode2);
                }
                treeNode.addChild(treeNode1);
            }
            root.addChild(treeNode);
        }

**Comment by 1455459550** [comment]
谢谢 大佬 能及时恢复我的信息 但是的类的方法可多都没有注释  大家也都不知道呀

**Comment by shineM** [comment]
客气。目前文档比较粗糙，如果可以的话可以帮忙提 Pull Request，😁

**Comment by 1455459550** [comment]
请问下 我要加载自己的数据需要改数据源和MyNodeViewFactory还有FirstLevelNodeViewBinder 这个？

**Comment by 1455459550** [comment]
我改完这个三个一直没有数据源 但是我在解析得到的数据是有的

**Comment by shineM** [comment]
按我的理解数据源应该是指 buildTree() ？你自己想怎么改怎么改吧

**Comment by 1455459550** [comment]
我在你的 buildTree() 设置了数据源 可是不管这样没法传过去给FirstLevelNodeViewBinder

**Comment by 1455459550** [comment]
打印数据源就是0

**Comment by 1455459550** [comment]
//                    解析拿到的数据源
                    shopCartBean= (ShopCartBean) msg.obj;
                    for (int i = 0; i < shopCartBean.getShopls().size(); i++) {
                        TreeNode treeNode = new TreeNode(shopCartBean.getShopls());
                        treeNode.setLevel(0);
//           设置默认展开第一个节点 并不能折叠
                        treeNode.setExpanded(true);
                        treeNode.setItemClickEnable(false);
                        for (int j = 0; j < shopCartBean.getShopls().get(i).getGoods().size(); j++) {
                            TreeNode treeNode1 = new TreeNode(shopCartBean.getShopls().get(i).getGoods());
                            treeNode1.setLevel(1);
                            for (int k = 0; k < shopCartBean.getShopls().get(i).getGoods().get(j).getAttr().size(); k++) {
                                TreeNode treeNode2 = new TreeNode(shopCartBean.getShopls().get(i).getGoods().get(j).getAttr());
                                treeNode2.setLevel(2);
                                treeNode1.addChild(treeNode2);
                            }
                            treeNode.addChild(treeNode1);
                        }
                        root.addChild(treeNode);
                    }
                    treeView = new TreeView(root, MainActivity.this, new MyNodeViewFactory());
                    View view = treeView.getView();
                    view.setLayoutParams(new ViewGroup.LayoutParams(
                            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
                    viewGroup.addView(view);

**Comment by 1455459550** [comment]
这是myNodeFac里面的

public class MyNodeViewFactory extends BaseNodeViewFactory {
    List< ShopCartBean.ShoplsBean> list;
    @Override
    public BaseNodeViewBinder getNodeViewBinder(View view, int level) {
        switch (level) {
            case 0:
                list=new ShopCartBean().getShopls();
                return new FirstLevelNodeViewBinder(view,list);
            case 1:
                return new SecondLevelNodeViewBinder(view);
            case 2:
                return new ThirdLevelNodeViewBinder(view);
            default:
                return null;
        }
    }
}
