### ISSUE TITLE
如果不知道有多少子节点呢

### ISSUE THREAD

**Issue by sylarzhang** [shineM/TreeView#28]
比如不知道有多少层（根据网络进行请求，有子节点就返回数据进行展示，没有就结束），也就不能通过switch来判断，也就不能新建子节点的viewbinder，萌新问一下大佬这个该怎么处理。thanks。

**Comment by shineM** [comment]
你肯定知道每一层应该长什么样吧？

**Comment by sylarzhang** [comment]
每一层都是一样的
 @Override
    public BaseNodeViewBinder getNodeViewBinder(View view, int level) {
        switch (level) {
            case 0:
                return new FirstLevelNodeViewBinder(view);
            case 1:
                return new SecondLevelNodeViewBinder(view);
            case 2:
                return new ThirdLevelNodeViewBinder(view);
            default:
                return null;
        }
    }

private void buildTree() {
        for (int i = 0; i < 20; i++) {
            TreeNode treeNode = new TreeNode(new String("Parent  " + "No." + i));
            treeNode.setLevel(0);
            for (int j = 0; j < 10; j++) {
                TreeNode treeNode1 = new TreeNode(new String("Child " + "No." + j));
                treeNode1.setLevel(1);
                for (int k = 0; k < 5; k++) {
                    TreeNode treeNode2 = new TreeNode(new String("Grand Child " + "No." + k));
                    treeNode2.setLevel(2);
                    treeNode1.addChild(treeNode2);
                }
                treeNode.addChild(treeNode1);
            }
            root.addChild(treeNode);
        }
貌似想到了，这两个都改成递归应该可以解决问题了，布局一样的话。感谢

**Comment by shineM** [comment]
让 factory 直接 return 同一个 ViewHolder 就好了吧

**Comment by sylarzhang** [comment]
差不多，还是有点点区别来着~~ 谢谢大大提供思路
