### ISSUE TITLE
How to delete all treenode and refill data again ?, i am using retrofit data to get data and when i am swiperefresh the data is double

### ISSUE THREAD

**Issue by ricodidan** [shineM/TreeView#35]
public void getListProductCatalog() {
        ll_productcatalog.setVisibility(View.GONE);
        tv_emptyproductcatalog.setVisibility(View.VISIBLE);
        tv_emptyproductcatalog.setText("Loading...");
        srl_refresh_productcatalog.setRefreshing(true);

        apiServiceEndPointMIS.getListProductCatalog(misApplication.getSessionManager().getToken())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.io())
                .subscribe(new Observer<Response<ListProductCatalogResponse>>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Response<ListProductCatalogResponse> listProductCatalogResponseResponse) {
                        if (listProductCatalogResponseResponse.code() == 200) {
                            srl_refresh_productcatalog.setRefreshing(false);
                            if (listProductCatalogResponseResponse.body().isStatus()) {

                                if (listProductCatalogResponseResponse.body().getData() != null && listProductCatalogResponseResponse.body().getData().size() > 0) {
                                    ll_productcatalog.setVisibility(View.VISIBLE);
                                    tv_emptyproductcatalog.setVisibility(View.GONE);

                                    if (listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog() != null && listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().size() > 0){
                                        for (int i = 0; i < listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().size(); i++) {
                                            TreeNode treeNode = new TreeNode(new String(listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getCompany().getCompany_id()+
                                                    " - "+listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getCompany().getCompany_name()));
                                            treeNode.setLevel(0);
                                            for (int j = 0; j < listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().size(); j++) {
                                                TreeNode treeNode1 = new TreeNode(new String(listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_sdm_id()+
                                                        " - "+listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_sdm_name()));
                                                treeNode1.setLevel(1);
                                                for (int k = 0; k < listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().size(); k++) {
                                                    TreeNode treeNode2 = new TreeNode(new String(listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_prt_id()+
                                                            " - "+listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_prt_name()));
                                                    treeNode2.setLevel(2);
                                                    for (int l = 0; l < listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_sdm_sub().size(); l++) {
                                                        TreeNode treeNode3 = new TreeNode(new String(listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_sdm_sub().get(l).getPrd_sdm_sub_id()+
                                                                " - "+listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_sdm_sub().get(l).getPrd_sdm_sub_name()));
                                                        treeNode3.setLevel(3);
                                                        for (int m = 0; m < listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_sdm_sub().get(l).getProduct().size(); m++) {
                                                            TreeNode treeNode4 = new TreeNode(new String(listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_sdm_sub().get(l).getProduct().get(m).getPrd_id()+
                                                                    " - "+listProductCatalogResponseResponse.body().getData().get(0).getProduct_catalog().get(i).getPrd_sdm().get(j).getPrd_prt().get(k).getPrd_sdm_sub().get(l).getProduct().get(m).getPrd_name()));
                                                            treeNode4.setLevel(4);
                                                            treeNode3.addChild(treeNode4);
                                                        }
                                                        treeNode2.addChild(treeNode3);
                                                    }
                                                    treeNode1.addChild(treeNode2);
                                                }
                                                treeNode.addChild(treeNode1);
                                            }
                                            root.addChild(treeNode);
                                        }
                                    }

                                    treeView = new TreeView(root, ProductCatalogActivity.this, new MyNodeViewFactoryProductCatalog());
                                    treeView.setItemAnimator(new DefaultItemAnimator());
                                    View view = treeView.getView();
                                    view.setLayoutParams(new ViewGroup.LayoutParams(
                                            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
                                    viewGroup.addView(view);

                                    treeView.expandAll();

                                } else {
                                    ll_productcatalog.setVisibility(View.GONE);
                                    tv_emptyproductcatalog.setVisibility(View.VISIBLE);
                                    tv_emptyproductcatalog.setText("Empty Data");
                                }

                            } else {
                                ll_productcatalog.setVisibility(View.GONE);
                                tv_emptyproductcatalog.setVisibility(View.VISIBLE);
                                tv_emptyproductcatalog.setText("Session time out, please re-login!");
                                misApplication.showToast("Session time out, please re-login!");
                            }

                        } else {
                            srl_refresh_productcatalog.setRefreshing(false);
                            ll_productcatalog.setVisibility(View.GONE);
                            tv_emptyproductcatalog.setVisibility(View.VISIBLE);
                            tv_emptyproductcatalog.setText("There is a problem with the internal server, please contact support application!");
                            misApplication.showToast("There is a problem with the internal server, please contact support application!");
                        }
                    }

                    @Override
                    public void onError(Throwable e) {
                        srl_refresh_productcatalog.setRefreshing(false);
                        System.out.println("ERROR" + e.getMessage());
                        ll_productcatalog.setVisibility(View.GONE);
                        tv_emptyproductcatalog.setVisibility(View.VISIBLE);
                        tv_emptyproductcatalog.setText("An error occurred, check your internet connection again!");
                        misApplication.showToast("An error occurred, check your internet connection again!");
                    }

                    @Override
                    public void onComplete() {

                    }
                });
    }

![image](https://user-images.githubusercontent.com/22855247/43311971-2632b290-91b6-11e8-9976-66b5eb995167.png)

**Comment by ALXKAY** [comment]
Add this `TreeNode root = TreeNode.root();` to the top of the `onNext(...)` method.

**Comment by ricodidan** [comment]
oke it's work, thank you mate
