### ISSUE TITLE
获取选中下标   getIndex作用域     应该是  public  而不是  private

### ISSUE THREAD

**Issue by xie438305665** [shineM/TreeView#43]
![tim 20181213160429](https://user-images.githubusercontent.com/19592766/49924302-e6a55080-fef0-11e8-89ac-7bf19b4bc916.png)

**Comment by shineM** [comment]
Fixed in [commit](https://github.com/shineM/TreeView/commit/5137b376be75793c530fce191f56ff4e59622424)
