### ISSUE TITLE
这个树形控件可以添加header与footer吗？

### ISSUE THREAD

**Issue by MagicKim** [shineM/TreeView#45]
现在项目上面要用，担心添加了头尾布局会影响树形列表的刷新，删除等操作，

**Comment by shineM** [comment]
目前没有实现现成的 API，不过一个简单的方式是给第一级 ViewHolder 设置多个布局，在 bind  的时候根据是否是 header/footer 来控制布局的显示隐藏

**Comment by MagicKim** [comment]
好的，O(∩_∩)O谢谢
