### ISSUE TITLE
两个问题，请尽快回复，比较着急。谢谢

### ISSUE THREAD

**Issue by choubaguai** [shineM/TreeView#5]
1，我的展开合上的图标在展开的时候没有反应，没看到相关代码，
2，最小层的点击事件如何实现，没有看到相关代码，没有相关说明。
麻烦大兄弟快点回复我，真的谢谢了。

**Comment by shineM** [comment]
查看https://github.com/shineM/TreeView/blob/master/app/src/main/java/me/texy/treeviewdemo/FirstLevelNodeViewBinder.java
1.onNodeToggled方法 监听展开收起
2.bindView方法  点击事件在这里实现
