### ISSUE TITLE
加载数据卡顿

### ISSUE THREAD

**Issue by zhaozeyx** [shineM/TreeView#50]
公司做压测，造了很多的数据，现在的情况是在设置数据的时候会卡住，滑动的时候没有问题，我想问下可能的原因在哪里？

**Comment by shineM** [comment]
打下 log 看下各个阶段耗时？如果滑动没问题像是构造 TreeNode 太耗时

**Comment by zhaozeyx** [comment]
这个问题，应该是我自己造成的，由于NestedScrollVIew嵌套RecyclerVIew导致
