### ISSUE TITLE
Why  Failed to resolve: me.texy.treeview:treeview_lib:1.0.3

### ISSUE THREAD

**Issue by AndyJaa** [shineM/TreeView#8]

**Comment by shineM** [comment]
Did you enable the gradle offline mode? plz attach the detail error log

**Comment by AndyJaa** [comment]
Thx,The problem has been solved.but the lib's minSdkVersion is 15,and i want to use it in my app(minSdkVersion is 11,and i can't edit it).==

**Comment by shineM** [comment]
Maybe you can download the lib and include it in your app as a module，then you can edit everything of the lib.
